package com.example.explosiverobot.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.explosiverobot.modle.ActionItem;
import com.example.explosiverobot.modle.ActionTab;
import com.example.explosiverobot.modle.ChatMessageBean;

import com.example.explosiverobot.db.ActionItemDao;
import com.example.explosiverobot.db.ActionTabDao;
import com.example.explosiverobot.db.ChatMessageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig actionItemDaoConfig;
    private final DaoConfig actionTabDaoConfig;
    private final DaoConfig chatMessageBeanDaoConfig;

    private final ActionItemDao actionItemDao;
    private final ActionTabDao actionTabDao;
    private final ChatMessageBeanDao chatMessageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        actionItemDaoConfig = daoConfigMap.get(ActionItemDao.class).clone();
        actionItemDaoConfig.initIdentityScope(type);

        actionTabDaoConfig = daoConfigMap.get(ActionTabDao.class).clone();
        actionTabDaoConfig.initIdentityScope(type);

        chatMessageBeanDaoConfig = daoConfigMap.get(ChatMessageBeanDao.class).clone();
        chatMessageBeanDaoConfig.initIdentityScope(type);

        actionItemDao = new ActionItemDao(actionItemDaoConfig, this);
        actionTabDao = new ActionTabDao(actionTabDaoConfig, this);
        chatMessageBeanDao = new ChatMessageBeanDao(chatMessageBeanDaoConfig, this);

        registerDao(ActionItem.class, actionItemDao);
        registerDao(ActionTab.class, actionTabDao);
        registerDao(ChatMessageBean.class, chatMessageBeanDao);
    }
    
    public void clear() {
        actionItemDaoConfig.clearIdentityScope();
        actionTabDaoConfig.clearIdentityScope();
        chatMessageBeanDaoConfig.clearIdentityScope();
    }

    public ActionItemDao getActionItemDao() {
        return actionItemDao;
    }

    public ActionTabDao getActionTabDao() {
        return actionTabDao;
    }

    public ChatMessageBeanDao getChatMessageBeanDao() {
        return chatMessageBeanDao;
    }

}
